#ifndef LSM9DS1_READ_IMU_H
#define LSM9DS1_READ_IMU_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "lsm9ds1_reg.h"   /* driver ST (for types like lsm9ds1_id_t) */

/*
 * NOTE:
 * - This header expects that your project already provides:
 *     - I2C handle (e.g. hi2c1) declared in i2c.h
 *     - UART handle (e.g. huart2) declared in usart.h or uart.h
 *   These are normally generated by CubeMX.
 *
 * - If your project uses different names (e.g. uart.h instead of usart.h),
 *   include the correct HAL headers in the .c file that implements the driver.
 */

/* ---------- Bus structure ---------- */
/* Represents the bus/context used to access the IMU (I2C handler + address). */
typedef struct {
  void   *hbus;        /* pointer to HAL bus handle (e.g. &hi2c1) */
  uint8_t i2c_address; /* 7/8-bit device address (driver uses 8-bit addresses macros) */
} sensbus_t;

/* Public API */

/**
 * @brief  Start polling read loop for LSM9DS1 IMU (accelerometer + gyroscope).
 * @note   This function contains an infinite loop that reads the IMU periodically
 *         and sends formatted data via UART using the platform tx_com implementation.
 *         Call this from main after peripherals initialization (I2C + UART).
 */
void lsm9ds1_read_imu_polling(void);

#ifdef __cplusplus
}
#endif

#endif /* LSM9DS1_READ_IMU_H */
